import { Product } from './db';

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Handcrafted Wooden Dining Table',
    description: 'Premium solid wood dining table, perfect for family gatherings. Crafted with traditional techniques and finished with eco-friendly varnish.',
    price: 25000,
    image: 'https://images.unsplash.com/photo-1551632786-de41ec802fcb?w=500&h=500&fit=crop',
    category: 'Dining',
    materials: ['Sheesham', 'Walnut', 'Oak'],
    colors: ['Natural Brown', 'Dark Walnut', 'Light Oak'],
    sizes: ['4 Seater', '6 Seater', '8 Seater'],
    rating: 4.5,
    reviewCount: 12,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Artisan Bed Frame',
    description: 'Elegant wooden bed frame with intricate carving details. Provides excellent support and durability for years of comfort.',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=500&h=500&fit=crop',
    category: 'Bedroom',
    materials: ['Teak', 'Sheesham', 'Mango Wood'],
    colors: ['Natural Brown', 'Dark Teak', 'Light Wood'],
    sizes: ['Single', 'Double', 'Queen'],
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Modern Office Chair',
    description: 'Comfortable wooden office chair with ergonomic design. Perfect for long working hours with stylish appearance.',
    price: 12000,
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500&h=500&fit=crop',
    category: 'Office',
    materials: ['Walnut', 'Oak', 'Beech'],
    colors: ['Natural Brown', 'Dark Walnut', 'Light Wood'],
    sizes: ['Standard', 'Large'],
    rating: 4.3,
    reviewCount: 8,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Decorative Wall Shelf',
    description: 'Beautiful wooden wall shelf with rustic charm. Great for displaying books, plants, and decorative items.',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1594620302200-25f5ad11d033?w=500&h=500&fit=crop',
    category: 'Decor',
    materials: ['Reclaimed Wood', 'Oak', 'Walnut'],
    colors: ['Natural Brown', 'Dark Walnut', 'Rustic Black'],
    sizes: ['Small', 'Medium', 'Large'],
    rating: 4.6,
    reviewCount: 15,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Coffee Table',
    description: 'Elegant coffee table with clean lines. Perfect centerpiece for your living room with ample storage space.',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&h=500&fit=crop',
    category: 'Living Room',
    materials: ['Sheesham', 'Teak', 'Walnut'],
    colors: ['Natural Brown', 'Dark Walnut', 'Light Teak'],
    sizes: ['Small', 'Large'],
    rating: 4.4,
    reviewCount: 10,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Bookshelf Unit',
    description: 'Spacious wooden bookshelf with multiple compartments. Ideal for organizing books and displaying collections.',
    price: 18000,
    image: 'https://images.unsplash.com/photo-1450604882657-007e26fbed46?w=500&h=500&fit=crop',
    category: 'Storage',
    materials: ['Plywood', 'Sheesham', 'Oak'],
    colors: ['Natural Brown', 'Dark Walnut', 'Light Oak'],
    sizes: ['4 Shelf', '5 Shelf', '6 Shelf'],
    rating: 4.5,
    reviewCount: 14,
    inStock: true,
    createdAt: new Date().toISOString(),
  },
];
